# Server Configuration
server.port=8080

# Service Information
otel.service.name=java-spring-boot-manual
otel.service.version=1.0.0

# OpenTelemetry Exporter Endpoints
otel.exporter.otlp.traces.endpoint=http://localhost:4338/v1/traces
otel.exporter.otlp.metrics.endpoint=http://localhost:4318/v1/metrics
otel.exporter.otlp.logs.endpoint=http://localhost:4328/v1/logs

# Logging
logging.level.root=INFO
logging.level.com.sematext.examples=INFO

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
